Repository 1up-lab/OneupUploaderBundle, pull requests merged in 2022-07, with the labels that each got.

#391 Make ResponseInterface extends \ArrayAccess
  src/Uploader/Response/ResponseInterface.php
Labels: bug, bc-break

#416 Add native return type declaration to Configuration::getConfigTreeBuilder
  src/DependencyInjection/Configuration.php
Labels: bug

#412 Support for flysystem v2
  README.md
  composer.json
  src/Uploader/Chunk/Storage/FlysystemStorage.php
  src/Uploader/File/FlysystemFile.php
  src/Uploader/Storage/FlysystemOrphanageStorage.php
  src/Uploader/Storage/FlysystemStorage.php
  tests/Uploader/Chunk/Storage/FlysystemStorageTest.php
  tests/Uploader/Storage/FlysystemOrphanageStorageTest.php
  tests/Uploader/Storage/FlysystemStorageTest.php
Labels: enhancement, bc-break

#427 quick fix #422 PHP 8.1 compatibility / deprecation warnings
  src/Uploader/Response/AbstractResponse.php
Labels: bug
